# Para definir el puerto donde "escuchará" el servidor
server.port=8080

# Para eliminar mensajes invasivos de Spring al iniciar
spring.main.banner-mode=off

# En desarrollo el "cache" del servidor debe estar en false para ver cambios al refrescar
spring.thymeleaf.cache=false